version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: cloudspire-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: cloudspire-order-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order_db
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  order-db-data: